version: "3.9"
services:
  database:
    image: 'percona:8.0'
    platform: linux/x86_64
    container_name: db-master
    volumes:
      - ./db-replication/master.cnf:/etc/my.cnf.d/repl.cnf
      - ./db-replication/master.sql:/docker-entrypoint-initdb.d/start.sql
      - ./../mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=otus_social_network
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"
  slave_1:
    image: 'percona:8.0'
    platform: linux/x86_64
    container_name: db-slave1
    volumes:
      - ./db-replication/slave.cnf:/etc/my.cnf.d/repl.cnf
      - ./db-replication/slave.sql:/docker-entrypoint-initdb.d/start.sql
      - ./../mysql_slave:/var/lib/mysql
    depends_on:
      - database
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3307:3306"
  backend:
    build:
      context: .
      dockerfile: ./src/Otus.SocialNetwork/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - database
      - slave_1
    ports:
      - 5005:80
  web:
    build:
      context: .
      dockerfile: ./src/Otus.SocialNetwork.Web/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - backend
    ports:
      - "80:80"
  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - backend
  #     - web
  #   ports:
  #     - "80:80"