version: "3.9"
services:
  database:
    image: mysql
    environment:
      - MYSQL_DATABASE=otus_social_network
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - ./../mysql:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: ./src/Otus.SocialNetwork/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    depends_on:
      - database
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"